package com.wonderrobot.sfhanbaizaikokanrishisutemu.entity.A010;



/**
 * @project
 *     null
 * @comment
 *     table id: A010W2I00015PrintEntity
 * @version

 */
public class A010W2I00015PrintEntity {
   /**
	*	 MITSUMORI_MITSUMORISHONO1 見積書NO
	*/
	private String MITSUMORI_MITSUMORISHONO1;
   /**
	*	 MITSUMORI_HINMEI2 品名
	*/
	private String MITSUMORI_HINMEI2;
   /**
	*	 MITSUMORI_GOUKEI3 合計
	*/
	private String MITSUMORI_GOUKEI3;
   /**
	*	 MITSUMORI_TEISHUTSUBI4 提出日
	*/
	private String MITSUMORI_TEISHUTSUBI4;
   /**
	*	 CHUUBUNSHO_SHANAIKOUJIBANGOU5 社内工事番号
	*/
	private String CHUUBUNSHO_SHANAIKOUJIBANGOU5;
   /**
	*	 CHUUBUNSHO_KYAKUSAKITANTOU6 客先担当
	*/
	private String CHUUBUNSHO_KYAKUSAKITANTOU6;
   /**
	*	 SHAIN_SHAINMEI7 社員名
	*/
	private String SHAIN_SHAINMEI7;
   /**
	*	 KAISHA_KAISHAMEI8 会社名
	*/
	private String KAISHA_KAISHAMEI8;
   /**
	* MITSUMORI_MITSUMORISHONO1 見積書NOを設定
	*
	* @param MITSUMORI_MITSUMORISHONO1 見積書NO
	*/
	public void setMITSUMORI_MITSUMORISHONO1(String MITSUMORI_MITSUMORISHONO1) {
		this.MITSUMORI_MITSUMORISHONO1 = MITSUMORI_MITSUMORISHONO1;
	}

   /**
	* MITSUMORI_MITSUMORISHONO1 見積書NOを取得
	*
	* @return MITSUMORI_MITSUMORISHONO1 見積書NO
	*/
	public String getMITSUMORI_MITSUMORISHONO1() {
		return this.MITSUMORI_MITSUMORISHONO1;
	}

   /**
	* MITSUMORI_HINMEI2 品名を設定
	*
	* @param MITSUMORI_HINMEI2 品名
	*/
	public void setMITSUMORI_HINMEI2(String MITSUMORI_HINMEI2) {
		this.MITSUMORI_HINMEI2 = MITSUMORI_HINMEI2;
	}

   /**
	* MITSUMORI_HINMEI2 品名を取得
	*
	* @return MITSUMORI_HINMEI2 品名
	*/
	public String getMITSUMORI_HINMEI2() {
		return this.MITSUMORI_HINMEI2;
	}

   /**
	* MITSUMORI_GOUKEI3 合計を設定
	*
	* @param MITSUMORI_GOUKEI3 合計
	*/
	public void setMITSUMORI_GOUKEI3(String MITSUMORI_GOUKEI3) {
		this.MITSUMORI_GOUKEI3 = MITSUMORI_GOUKEI3;
	}

   /**
	* MITSUMORI_GOUKEI3 合計を取得
	*
	* @return MITSUMORI_GOUKEI3 合計
	*/
	public String getMITSUMORI_GOUKEI3() {
		return this.MITSUMORI_GOUKEI3;
	}

   /**
	* MITSUMORI_TEISHUTSUBI4 提出日を設定
	*
	* @param MITSUMORI_TEISHUTSUBI4 提出日
	*/
	public void setMITSUMORI_TEISHUTSUBI4(String MITSUMORI_TEISHUTSUBI4) {
		this.MITSUMORI_TEISHUTSUBI4 = MITSUMORI_TEISHUTSUBI4;
	}

   /**
	* MITSUMORI_TEISHUTSUBI4 提出日を取得
	*
	* @return MITSUMORI_TEISHUTSUBI4 提出日
	*/
	public String getMITSUMORI_TEISHUTSUBI4() {
		return this.MITSUMORI_TEISHUTSUBI4;
	}

   /**
	* CHUUBUNSHO_SHANAIKOUJIBANGOU5 社内工事番号を設定
	*
	* @param CHUUBUNSHO_SHANAIKOUJIBANGOU5 社内工事番号
	*/
	public void setCHUUBUNSHO_SHANAIKOUJIBANGOU5(String CHUUBUNSHO_SHANAIKOUJIBANGOU5) {
		this.CHUUBUNSHO_SHANAIKOUJIBANGOU5 = CHUUBUNSHO_SHANAIKOUJIBANGOU5;
	}

   /**
	* CHUUBUNSHO_SHANAIKOUJIBANGOU5 社内工事番号を取得
	*
	* @return CHUUBUNSHO_SHANAIKOUJIBANGOU5 社内工事番号
	*/
	public String getCHUUBUNSHO_SHANAIKOUJIBANGOU5() {
		return this.CHUUBUNSHO_SHANAIKOUJIBANGOU5;
	}

   /**
	* CHUUBUNSHO_KYAKUSAKITANTOU6 客先担当を設定
	*
	* @param CHUUBUNSHO_KYAKUSAKITANTOU6 客先担当
	*/
	public void setCHUUBUNSHO_KYAKUSAKITANTOU6(String CHUUBUNSHO_KYAKUSAKITANTOU6) {
		this.CHUUBUNSHO_KYAKUSAKITANTOU6 = CHUUBUNSHO_KYAKUSAKITANTOU6;
	}

   /**
	* CHUUBUNSHO_KYAKUSAKITANTOU6 客先担当を取得
	*
	* @return CHUUBUNSHO_KYAKUSAKITANTOU6 客先担当
	*/
	public String getCHUUBUNSHO_KYAKUSAKITANTOU6() {
		return this.CHUUBUNSHO_KYAKUSAKITANTOU6;
	}

   /**
	* SHAIN_SHAINMEI7 社員名を設定
	*
	* @param SHAIN_SHAINMEI7 社員名
	*/
	public void setSHAIN_SHAINMEI7(String SHAIN_SHAINMEI7) {
		this.SHAIN_SHAINMEI7 = SHAIN_SHAINMEI7;
	}

   /**
	* SHAIN_SHAINMEI7 社員名を取得
	*
	* @return SHAIN_SHAINMEI7 社員名
	*/
	public String getSHAIN_SHAINMEI7() {
		return this.SHAIN_SHAINMEI7;
	}

   /**
	* KAISHA_KAISHAMEI8 会社名を設定
	*
	* @param KAISHA_KAISHAMEI8 会社名
	*/
	public void setKAISHA_KAISHAMEI8(String KAISHA_KAISHAMEI8) {
		this.KAISHA_KAISHAMEI8 = KAISHA_KAISHAMEI8;
	}

   /**
	* KAISHA_KAISHAMEI8 会社名を取得
	*
	* @return KAISHA_KAISHAMEI8 会社名
	*/
	public String getKAISHA_KAISHAMEI8() {
		return this.KAISHA_KAISHAMEI8;
	}


}