package com.wonderrobot.sfhanbaizaikokanrishisutemu.dao.A013;
import org.springframework.stereotype.Repository;
import com.wonderrobot.sfhanbaizaikokanrishisutemu.mapper.A013.A013T7afterupdateBUHINMapper;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * @project
 *     SF販売在庫管理システム
 * @comment
 *      class: A013T7afterupdateBUHINDao
 * @version

 */

@Repository
public class A013T7afterupdateBUHINDao {
	@Autowired
	private A013T7afterupdateBUHINMapper A013T7afterupdateBUHINMapper;

   
	public int A013T7afterupdateBUHIN (String ay3_BUHINSYOUSAIRINJIHYOU_KYAKUSAKIMEISHOU, String ay3_BUHINSYOUSAIRINJIHYOU_HINBAN, String ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU, String ay3_BUHINSYOUSAIRINJIHYOU_ASENBURIRAIN, String ay3_BUHINSYOUSAIRINJIHYOU_KIKAIMEISHOU, String ay3_BUHINSYOUSAIRINJIHYOU_BUHINMEISHOU, int ay3_BUHINSYOUSAIRINJIHYOU_SEISAKUSUU, String ay3_BUHINSYOUSAIRINJIHYOU_TANTOUSHA, String ay3_BUHINSYOUSAIRINJIHYOU_MAISUU, String ay3_BUHINSYOUSAIRINJIHYOU_HIDZUKE, String BUHINCHUUBUNSHONO, String BUHINCHUUBUNSHOMEISAINO) throws Exception {

		int returnVal = A013T7afterupdateBUHINMapper.A013T7afterupdateBUHIN(ay3_BUHINSYOUSAIRINJIHYOU_KYAKUSAKIMEISHOU,ay3_BUHINSYOUSAIRINJIHYOU_HINBAN,ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU,ay3_BUHINSYOUSAIRINJIHYOU_ASENBURIRAIN,ay3_BUHINSYOUSAIRINJIHYOU_KIKAIMEISHOU,ay3_BUHINSYOUSAIRINJIHYOU_BUHINMEISHOU,ay3_BUHINSYOUSAIRINJIHYOU_SEISAKUSUU,ay3_BUHINSYOUSAIRINJIHYOU_TANTOUSHA,ay3_BUHINSYOUSAIRINJIHYOU_MAISUU,ay3_BUHINSYOUSAIRINJIHYOU_HIDZUKE,BUHINCHUUBUNSHONO,BUHINCHUUBUNSHOMEISAINO);
		return returnVal;
	}
}