package com.wonderrobot.sfhanbaizaikokanrishisutemu.entity.A008;



/**
 * @project
 *     null
 * @comment
 *     table id: A008Q2I00012PrintEntity
 * @version

 */
public class A008Q2I00012PrintEntity {
   /**
	*	 RYOUSHUUSHOVIEW_CHUUBUNSHONO1 注文書NO
	*/
	private String RYOUSHUUSHOVIEW_CHUUBUNSHONO1;
   /**
	*	 YOUSHUUSHOVIEW_MITSUMORISHONO2 見積書NO
	*/
	private String YOUSHUUSHOVIEW_MITSUMORISHONO2;
   /**
	*	 SHUUSHOVIEW_SHANAIKOUJIBANGOU3 社内工事番号
	*/
	private String SHUUSHOVIEW_SHANAIKOUJIBANGOU3;
   /**
	*	 RYOUSHUUSHOVIEW_KAISHAMEI4 会社名
	*/
	private String RYOUSHUUSHOVIEW_KAISHAMEI4;
   /**
	*	 YOUSHUUSHOVIEW_NYUUKINKINGAKU5 入金金額
	*/
	private String YOUSHUUSHOVIEW_NYUUKINKINGAKU5;
   /**
	*	 UUSHOVIEW_FURIDASHIZUMIWARIAI6 振出済み割合
	*/
	private String UUSHOVIEW_FURIDASHIZUMIWARIAI6;
   /**
	*	 USHOVIEW_FURIDASHIZUMIHIDZUKE7 振出済み日付
	*/
	private String USHOVIEW_FURIDASHIZUMIHIDZUKE7;
   /**
	*	 USHOVIEW_FURIDASHIZUMIKINGAKU8 振出済み金額
	*/
	private String USHOVIEW_FURIDASHIZUMIKINGAKU8;
   /**
	*	 SHUUSHOVIEW_MIFURIDASHIWARIAI9 未振出割合
	*/
	private String SHUUSHOVIEW_MIFURIDASHIWARIAI9;
   /**
	*	 UUSHOVIEW_MIFURIDASHIKINGAKU10 未振出金額
	*/
	private String UUSHOVIEW_MIFURIDASHIKINGAKU10;
   /**
	*	 HUUSHOVIEW_NYUUKINZUMIWARIAI11 入金済み割合
	*/
	private String HUUSHOVIEW_NYUUKINZUMIWARIAI11;
   /**
	*	 UUSHOVIEW_NYUUKINZUMIKINGAKU12 入金済み金額
	*/
	private String UUSHOVIEW_NYUUKINZUMIKINGAKU12;
   /**
	*	 USHUUSHOVIEW_MINYUUKINWARIAI13 未入金割合
	*/
	private String USHUUSHOVIEW_MINYUUKINWARIAI13;
   /**
	*	 SHUUSHOVIEW_MINYUUKINKINGAKU14 未入金金額
	*/
	private String SHUUSHOVIEW_MINYUUKINKINGAKU14;
   /**
	*	 RYOUSHUUSHOVIEW_SHAINMEI15 社員名
	*/
	private String RYOUSHUUSHOVIEW_SHAINMEI15;
   /**
	* RYOUSHUUSHOVIEW_CHUUBUNSHONO1 注文書NOを設定
	*
	* @param RYOUSHUUSHOVIEW_CHUUBUNSHONO1 注文書NO
	*/
	public void setRYOUSHUUSHOVIEW_CHUUBUNSHONO1(String RYOUSHUUSHOVIEW_CHUUBUNSHONO1) {
		this.RYOUSHUUSHOVIEW_CHUUBUNSHONO1 = RYOUSHUUSHOVIEW_CHUUBUNSHONO1;
	}

   /**
	* RYOUSHUUSHOVIEW_CHUUBUNSHONO1 注文書NOを取得
	*
	* @return RYOUSHUUSHOVIEW_CHUUBUNSHONO1 注文書NO
	*/
	public String getRYOUSHUUSHOVIEW_CHUUBUNSHONO1() {
		return this.RYOUSHUUSHOVIEW_CHUUBUNSHONO1;
	}

   /**
	* YOUSHUUSHOVIEW_MITSUMORISHONO2 見積書NOを設定
	*
	* @param YOUSHUUSHOVIEW_MITSUMORISHONO2 見積書NO
	*/
	public void setYOUSHUUSHOVIEW_MITSUMORISHONO2(String YOUSHUUSHOVIEW_MITSUMORISHONO2) {
		this.YOUSHUUSHOVIEW_MITSUMORISHONO2 = YOUSHUUSHOVIEW_MITSUMORISHONO2;
	}

   /**
	* YOUSHUUSHOVIEW_MITSUMORISHONO2 見積書NOを取得
	*
	* @return YOUSHUUSHOVIEW_MITSUMORISHONO2 見積書NO
	*/
	public String getYOUSHUUSHOVIEW_MITSUMORISHONO2() {
		return this.YOUSHUUSHOVIEW_MITSUMORISHONO2;
	}

   /**
	* SHUUSHOVIEW_SHANAIKOUJIBANGOU3 社内工事番号を設定
	*
	* @param SHUUSHOVIEW_SHANAIKOUJIBANGOU3 社内工事番号
	*/
	public void setSHUUSHOVIEW_SHANAIKOUJIBANGOU3(String SHUUSHOVIEW_SHANAIKOUJIBANGOU3) {
		this.SHUUSHOVIEW_SHANAIKOUJIBANGOU3 = SHUUSHOVIEW_SHANAIKOUJIBANGOU3;
	}

   /**
	* SHUUSHOVIEW_SHANAIKOUJIBANGOU3 社内工事番号を取得
	*
	* @return SHUUSHOVIEW_SHANAIKOUJIBANGOU3 社内工事番号
	*/
	public String getSHUUSHOVIEW_SHANAIKOUJIBANGOU3() {
		return this.SHUUSHOVIEW_SHANAIKOUJIBANGOU3;
	}

   /**
	* RYOUSHUUSHOVIEW_KAISHAMEI4 会社名を設定
	*
	* @param RYOUSHUUSHOVIEW_KAISHAMEI4 会社名
	*/
	public void setRYOUSHUUSHOVIEW_KAISHAMEI4(String RYOUSHUUSHOVIEW_KAISHAMEI4) {
		this.RYOUSHUUSHOVIEW_KAISHAMEI4 = RYOUSHUUSHOVIEW_KAISHAMEI4;
	}

   /**
	* RYOUSHUUSHOVIEW_KAISHAMEI4 会社名を取得
	*
	* @return RYOUSHUUSHOVIEW_KAISHAMEI4 会社名
	*/
	public String getRYOUSHUUSHOVIEW_KAISHAMEI4() {
		return this.RYOUSHUUSHOVIEW_KAISHAMEI4;
	}

   /**
	* YOUSHUUSHOVIEW_NYUUKINKINGAKU5 入金金額を設定
	*
	* @param YOUSHUUSHOVIEW_NYUUKINKINGAKU5 入金金額
	*/
	public void setYOUSHUUSHOVIEW_NYUUKINKINGAKU5(String YOUSHUUSHOVIEW_NYUUKINKINGAKU5) {
		this.YOUSHUUSHOVIEW_NYUUKINKINGAKU5 = YOUSHUUSHOVIEW_NYUUKINKINGAKU5;
	}

   /**
	* YOUSHUUSHOVIEW_NYUUKINKINGAKU5 入金金額を取得
	*
	* @return YOUSHUUSHOVIEW_NYUUKINKINGAKU5 入金金額
	*/
	public String getYOUSHUUSHOVIEW_NYUUKINKINGAKU5() {
		return this.YOUSHUUSHOVIEW_NYUUKINKINGAKU5;
	}

   /**
	* UUSHOVIEW_FURIDASHIZUMIWARIAI6 振出済み割合を設定
	*
	* @param UUSHOVIEW_FURIDASHIZUMIWARIAI6 振出済み割合
	*/
	public void setUUSHOVIEW_FURIDASHIZUMIWARIAI6(String UUSHOVIEW_FURIDASHIZUMIWARIAI6) {
		this.UUSHOVIEW_FURIDASHIZUMIWARIAI6 = UUSHOVIEW_FURIDASHIZUMIWARIAI6;
	}

   /**
	* UUSHOVIEW_FURIDASHIZUMIWARIAI6 振出済み割合を取得
	*
	* @return UUSHOVIEW_FURIDASHIZUMIWARIAI6 振出済み割合
	*/
	public String getUUSHOVIEW_FURIDASHIZUMIWARIAI6() {
		return this.UUSHOVIEW_FURIDASHIZUMIWARIAI6;
	}

   /**
	* USHOVIEW_FURIDASHIZUMIHIDZUKE7 振出済み日付を設定
	*
	* @param USHOVIEW_FURIDASHIZUMIHIDZUKE7 振出済み日付
	*/
	public void setUSHOVIEW_FURIDASHIZUMIHIDZUKE7(String USHOVIEW_FURIDASHIZUMIHIDZUKE7) {
		this.USHOVIEW_FURIDASHIZUMIHIDZUKE7 = USHOVIEW_FURIDASHIZUMIHIDZUKE7;
	}

   /**
	* USHOVIEW_FURIDASHIZUMIHIDZUKE7 振出済み日付を取得
	*
	* @return USHOVIEW_FURIDASHIZUMIHIDZUKE7 振出済み日付
	*/
	public String getUSHOVIEW_FURIDASHIZUMIHIDZUKE7() {
		return this.USHOVIEW_FURIDASHIZUMIHIDZUKE7;
	}

   /**
	* USHOVIEW_FURIDASHIZUMIKINGAKU8 振出済み金額を設定
	*
	* @param USHOVIEW_FURIDASHIZUMIKINGAKU8 振出済み金額
	*/
	public void setUSHOVIEW_FURIDASHIZUMIKINGAKU8(String USHOVIEW_FURIDASHIZUMIKINGAKU8) {
		this.USHOVIEW_FURIDASHIZUMIKINGAKU8 = USHOVIEW_FURIDASHIZUMIKINGAKU8;
	}

   /**
	* USHOVIEW_FURIDASHIZUMIKINGAKU8 振出済み金額を取得
	*
	* @return USHOVIEW_FURIDASHIZUMIKINGAKU8 振出済み金額
	*/
	public String getUSHOVIEW_FURIDASHIZUMIKINGAKU8() {
		return this.USHOVIEW_FURIDASHIZUMIKINGAKU8;
	}

   /**
	* SHUUSHOVIEW_MIFURIDASHIWARIAI9 未振出割合を設定
	*
	* @param SHUUSHOVIEW_MIFURIDASHIWARIAI9 未振出割合
	*/
	public void setSHUUSHOVIEW_MIFURIDASHIWARIAI9(String SHUUSHOVIEW_MIFURIDASHIWARIAI9) {
		this.SHUUSHOVIEW_MIFURIDASHIWARIAI9 = SHUUSHOVIEW_MIFURIDASHIWARIAI9;
	}

   /**
	* SHUUSHOVIEW_MIFURIDASHIWARIAI9 未振出割合を取得
	*
	* @return SHUUSHOVIEW_MIFURIDASHIWARIAI9 未振出割合
	*/
	public String getSHUUSHOVIEW_MIFURIDASHIWARIAI9() {
		return this.SHUUSHOVIEW_MIFURIDASHIWARIAI9;
	}

   /**
	* UUSHOVIEW_MIFURIDASHIKINGAKU10 未振出金額を設定
	*
	* @param UUSHOVIEW_MIFURIDASHIKINGAKU10 未振出金額
	*/
	public void setUUSHOVIEW_MIFURIDASHIKINGAKU10(String UUSHOVIEW_MIFURIDASHIKINGAKU10) {
		this.UUSHOVIEW_MIFURIDASHIKINGAKU10 = UUSHOVIEW_MIFURIDASHIKINGAKU10;
	}

   /**
	* UUSHOVIEW_MIFURIDASHIKINGAKU10 未振出金額を取得
	*
	* @return UUSHOVIEW_MIFURIDASHIKINGAKU10 未振出金額
	*/
	public String getUUSHOVIEW_MIFURIDASHIKINGAKU10() {
		return this.UUSHOVIEW_MIFURIDASHIKINGAKU10;
	}

   /**
	* HUUSHOVIEW_NYUUKINZUMIWARIAI11 入金済み割合を設定
	*
	* @param HUUSHOVIEW_NYUUKINZUMIWARIAI11 入金済み割合
	*/
	public void setHUUSHOVIEW_NYUUKINZUMIWARIAI11(String HUUSHOVIEW_NYUUKINZUMIWARIAI11) {
		this.HUUSHOVIEW_NYUUKINZUMIWARIAI11 = HUUSHOVIEW_NYUUKINZUMIWARIAI11;
	}

   /**
	* HUUSHOVIEW_NYUUKINZUMIWARIAI11 入金済み割合を取得
	*
	* @return HUUSHOVIEW_NYUUKINZUMIWARIAI11 入金済み割合
	*/
	public String getHUUSHOVIEW_NYUUKINZUMIWARIAI11() {
		return this.HUUSHOVIEW_NYUUKINZUMIWARIAI11;
	}

   /**
	* UUSHOVIEW_NYUUKINZUMIKINGAKU12 入金済み金額を設定
	*
	* @param UUSHOVIEW_NYUUKINZUMIKINGAKU12 入金済み金額
	*/
	public void setUUSHOVIEW_NYUUKINZUMIKINGAKU12(String UUSHOVIEW_NYUUKINZUMIKINGAKU12) {
		this.UUSHOVIEW_NYUUKINZUMIKINGAKU12 = UUSHOVIEW_NYUUKINZUMIKINGAKU12;
	}

   /**
	* UUSHOVIEW_NYUUKINZUMIKINGAKU12 入金済み金額を取得
	*
	* @return UUSHOVIEW_NYUUKINZUMIKINGAKU12 入金済み金額
	*/
	public String getUUSHOVIEW_NYUUKINZUMIKINGAKU12() {
		return this.UUSHOVIEW_NYUUKINZUMIKINGAKU12;
	}

   /**
	* USHUUSHOVIEW_MINYUUKINWARIAI13 未入金割合を設定
	*
	* @param USHUUSHOVIEW_MINYUUKINWARIAI13 未入金割合
	*/
	public void setUSHUUSHOVIEW_MINYUUKINWARIAI13(String USHUUSHOVIEW_MINYUUKINWARIAI13) {
		this.USHUUSHOVIEW_MINYUUKINWARIAI13 = USHUUSHOVIEW_MINYUUKINWARIAI13;
	}

   /**
	* USHUUSHOVIEW_MINYUUKINWARIAI13 未入金割合を取得
	*
	* @return USHUUSHOVIEW_MINYUUKINWARIAI13 未入金割合
	*/
	public String getUSHUUSHOVIEW_MINYUUKINWARIAI13() {
		return this.USHUUSHOVIEW_MINYUUKINWARIAI13;
	}

   /**
	* SHUUSHOVIEW_MINYUUKINKINGAKU14 未入金金額を設定
	*
	* @param SHUUSHOVIEW_MINYUUKINKINGAKU14 未入金金額
	*/
	public void setSHUUSHOVIEW_MINYUUKINKINGAKU14(String SHUUSHOVIEW_MINYUUKINKINGAKU14) {
		this.SHUUSHOVIEW_MINYUUKINKINGAKU14 = SHUUSHOVIEW_MINYUUKINKINGAKU14;
	}

   /**
	* SHUUSHOVIEW_MINYUUKINKINGAKU14 未入金金額を取得
	*
	* @return SHUUSHOVIEW_MINYUUKINKINGAKU14 未入金金額
	*/
	public String getSHUUSHOVIEW_MINYUUKINKINGAKU14() {
		return this.SHUUSHOVIEW_MINYUUKINKINGAKU14;
	}

   /**
	* RYOUSHUUSHOVIEW_SHAINMEI15 社員名を設定
	*
	* @param RYOUSHUUSHOVIEW_SHAINMEI15 社員名
	*/
	public void setRYOUSHUUSHOVIEW_SHAINMEI15(String RYOUSHUUSHOVIEW_SHAINMEI15) {
		this.RYOUSHUUSHOVIEW_SHAINMEI15 = RYOUSHUUSHOVIEW_SHAINMEI15;
	}

   /**
	* RYOUSHUUSHOVIEW_SHAINMEI15 社員名を取得
	*
	* @return RYOUSHUUSHOVIEW_SHAINMEI15 社員名
	*/
	public String getRYOUSHUUSHOVIEW_SHAINMEI15() {
		return this.RYOUSHUUSHOVIEW_SHAINMEI15;
	}


}