package com.wonderrobot.sfhanbaizaikokanrishisutemu.dao.A013;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import com.wonderrobot.sfhanbaizaikokanrishisutemu.BaseTest;
import com.wonderrobot.sfhanbaizaikokanrishisutemu.dao.A013.A013T7afterinsertBUHINSYOUSAIDao;
import org.springframework.test.annotation.Rollback;
import org.junit.Assert;
import org.springframework.stereotype.Repository;
import com.wonderrobot.sfhanbaizaikokanrishisutemu.mapper.A013.A013T7afterinsertBUHINSYOUSAIMapper;

/**
 * @project
 *     SF販売在庫管理システム
 * @comment
 *      class: A013T7afterinsertBUHINSYOUSAIDao
 * @version

 */public class A013T7afterinsertBUHINSYOUSAIDaoTest extends BaseTest {


	@Autowired
	private A013T7afterinsertBUHINSYOUSAIDao A013T7afterinsertBUHINSYOUSAIDao;
	/**
	 * Test Methods
	 *
	 */
    @Test
    @Rollback
	public void A013T7afterinsertBUHINSYOUSAI () throws Exception {
		String ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUHINKUBUN = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_HINMEI = "1";
		int ay7_BUHINSYOUSAIRINJIHYOU_KOSUU = 0;
		int ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU = 0;
		String ay7_BUHINSYOUSAIRINJIHYOU_ZAISHITSU_KEISHIKI = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUSHA = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_BIKOU = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_KIBOUNOUKI = "1";
		double ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUTANKA = 0.0;
		String ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUHIDZUKE = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAHIDZUKE = "1";
		double ay7_BUHINSYOUSAIRINJIHYOU_SHOUKEI = 0.0;
		String ay7_BUHINSYOUSAIRINJIHYOU_TOUROKUSHAID = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_BIKOU1 = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_HITSUYOU = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_TEHAI = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_KANRYOU = "1";
		int ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU1 = 0;
		String ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAYOTEIBI = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_TANTOUSHAID = "1";
		String ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO1 = "1";
		String BUHINCHUUBUNSHONO = "1";
		String BUHINCHUUBUNSHOMEISAINO = "1";
		String ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU = "1";


		int returnVal = A013T7afterinsertBUHINSYOUSAIDao.A013T7afterinsertBUHINSYOUSAI(ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUHINKUBUN, ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO, ay7_BUHINSYOUSAIRINJIHYOU_HINMEI, ay7_BUHINSYOUSAIRINJIHYOU_KOSUU, ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU, ay7_BUHINSYOUSAIRINJIHYOU_ZAISHITSU_KEISHIKI, ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUSHA, ay7_BUHINSYOUSAIRINJIHYOU_BIKOU, ay7_BUHINSYOUSAIRINJIHYOU_KIBOUNOUKI, ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUTANKA, ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUHIDZUKE, ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAHIDZUKE, ay7_BUHINSYOUSAIRINJIHYOU_SHOUKEI, ay7_BUHINSYOUSAIRINJIHYOU_TOUROKUSHAID, ay7_BUHINSYOUSAIRINJIHYOU_BIKOU1, ay7_BUHINSYOUSAIRINJIHYOU_HITSUYOU, ay7_BUHINSYOUSAIRINJIHYOU_TEHAI, ay7_BUHINSYOUSAIRINJIHYOU_KANRYOU, ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU1, ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAYOTEIBI, ay7_BUHINSYOUSAIRINJIHYOU_TANTOUSHAID, ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO1, BUHINCHUUBUNSHONO, BUHINCHUUBUNSHOMEISAINO, ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU);
		Assert.assertTrue("データ新規時エラーが発生しました", returnVal > 0);
		System.out.println(returnVal);

	}

}