package com.wonderrobot.sfhanbaizaikokanrishisutemu.entity.A011;



/**
 * @project
 *     null
 * @comment
 *     table id: A011S4I00010PrintEntity
 * @version

 */
public class A011S4I00010PrintEntity {
   /**
	*	 CHUUBUNSHO_CHUUBUNSHONO1 注文書NO
	*/
	private String CHUUBUNSHO_CHUUBUNSHONO1;
   /**
	*	 CHUUBUNSHO_HINMEI2 品名
	*/
	private String CHUUBUNSHO_HINMEI2;
   /**
	*	 CHUUBUNSHO_KYAKUSAKIBUSHO3 客先部署
	*/
	private String CHUUBUNSHO_KYAKUSAKIBUSHO3;
   /**
	*	 CHUUBUNSHO_KYAKUSAKITANTOU4 客先担当
	*/
	private String CHUUBUNSHO_KYAKUSAKITANTOU4;
   /**
	*	 CHUUBUNSHO_CHUUMONHIDZUKE5 注文日付
	*/
	private String CHUUBUNSHO_CHUUMONHIDZUKE5;
   /**
	*	 CHUUBUNSHO_NOUKIYOTEIBI6 納期予定日
	*/
	private String CHUUBUNSHO_NOUKIYOTEIBI6;
   /**
	*	 CHUUBUNSHO_MITSUMORISHONO7 見積書NO
	*/
	private String CHUUBUNSHO_MITSUMORISHONO7;
   /**
	*	 CHUUBUNSHO_MITSUMORIKINGAKU8 見積金額
	*/
	private String CHUUBUNSHO_MITSUMORIKINGAKU8;
   /**
	*	 CHUUBUNSHO_SHOUHINSOUGAKUJPY9 商品総額JPY
	*/
	private String CHUUBUNSHO_SHOUHINSOUGAKUJPY9;
   /**
	*	 CHUUBUNSHO_NOUNYUUBI10 納入日
	*/
	private String CHUUBUNSHO_NOUNYUUBI10;
   /**
	*	 SHAIN_SHAINMEI11 社員名
	*/
	private String SHAIN_SHAINMEI11;
   /**
	*	 KAISHA_KAISHAMEI12 会社名
	*/
	private String KAISHA_KAISHAMEI12;
   /**
	* CHUUBUNSHO_CHUUBUNSHONO1 注文書NOを設定
	*
	* @param CHUUBUNSHO_CHUUBUNSHONO1 注文書NO
	*/
	public void setCHUUBUNSHO_CHUUBUNSHONO1(String CHUUBUNSHO_CHUUBUNSHONO1) {
		this.CHUUBUNSHO_CHUUBUNSHONO1 = CHUUBUNSHO_CHUUBUNSHONO1;
	}

   /**
	* CHUUBUNSHO_CHUUBUNSHONO1 注文書NOを取得
	*
	* @return CHUUBUNSHO_CHUUBUNSHONO1 注文書NO
	*/
	public String getCHUUBUNSHO_CHUUBUNSHONO1() {
		return this.CHUUBUNSHO_CHUUBUNSHONO1;
	}

   /**
	* CHUUBUNSHO_HINMEI2 品名を設定
	*
	* @param CHUUBUNSHO_HINMEI2 品名
	*/
	public void setCHUUBUNSHO_HINMEI2(String CHUUBUNSHO_HINMEI2) {
		this.CHUUBUNSHO_HINMEI2 = CHUUBUNSHO_HINMEI2;
	}

   /**
	* CHUUBUNSHO_HINMEI2 品名を取得
	*
	* @return CHUUBUNSHO_HINMEI2 品名
	*/
	public String getCHUUBUNSHO_HINMEI2() {
		return this.CHUUBUNSHO_HINMEI2;
	}

   /**
	* CHUUBUNSHO_KYAKUSAKIBUSHO3 客先部署を設定
	*
	* @param CHUUBUNSHO_KYAKUSAKIBUSHO3 客先部署
	*/
	public void setCHUUBUNSHO_KYAKUSAKIBUSHO3(String CHUUBUNSHO_KYAKUSAKIBUSHO3) {
		this.CHUUBUNSHO_KYAKUSAKIBUSHO3 = CHUUBUNSHO_KYAKUSAKIBUSHO3;
	}

   /**
	* CHUUBUNSHO_KYAKUSAKIBUSHO3 客先部署を取得
	*
	* @return CHUUBUNSHO_KYAKUSAKIBUSHO3 客先部署
	*/
	public String getCHUUBUNSHO_KYAKUSAKIBUSHO3() {
		return this.CHUUBUNSHO_KYAKUSAKIBUSHO3;
	}

   /**
	* CHUUBUNSHO_KYAKUSAKITANTOU4 客先担当を設定
	*
	* @param CHUUBUNSHO_KYAKUSAKITANTOU4 客先担当
	*/
	public void setCHUUBUNSHO_KYAKUSAKITANTOU4(String CHUUBUNSHO_KYAKUSAKITANTOU4) {
		this.CHUUBUNSHO_KYAKUSAKITANTOU4 = CHUUBUNSHO_KYAKUSAKITANTOU4;
	}

   /**
	* CHUUBUNSHO_KYAKUSAKITANTOU4 客先担当を取得
	*
	* @return CHUUBUNSHO_KYAKUSAKITANTOU4 客先担当
	*/
	public String getCHUUBUNSHO_KYAKUSAKITANTOU4() {
		return this.CHUUBUNSHO_KYAKUSAKITANTOU4;
	}

   /**
	* CHUUBUNSHO_CHUUMONHIDZUKE5 注文日付を設定
	*
	* @param CHUUBUNSHO_CHUUMONHIDZUKE5 注文日付
	*/
	public void setCHUUBUNSHO_CHUUMONHIDZUKE5(String CHUUBUNSHO_CHUUMONHIDZUKE5) {
		this.CHUUBUNSHO_CHUUMONHIDZUKE5 = CHUUBUNSHO_CHUUMONHIDZUKE5;
	}

   /**
	* CHUUBUNSHO_CHUUMONHIDZUKE5 注文日付を取得
	*
	* @return CHUUBUNSHO_CHUUMONHIDZUKE5 注文日付
	*/
	public String getCHUUBUNSHO_CHUUMONHIDZUKE5() {
		return this.CHUUBUNSHO_CHUUMONHIDZUKE5;
	}

   /**
	* CHUUBUNSHO_NOUKIYOTEIBI6 納期予定日を設定
	*
	* @param CHUUBUNSHO_NOUKIYOTEIBI6 納期予定日
	*/
	public void setCHUUBUNSHO_NOUKIYOTEIBI6(String CHUUBUNSHO_NOUKIYOTEIBI6) {
		this.CHUUBUNSHO_NOUKIYOTEIBI6 = CHUUBUNSHO_NOUKIYOTEIBI6;
	}

   /**
	* CHUUBUNSHO_NOUKIYOTEIBI6 納期予定日を取得
	*
	* @return CHUUBUNSHO_NOUKIYOTEIBI6 納期予定日
	*/
	public String getCHUUBUNSHO_NOUKIYOTEIBI6() {
		return this.CHUUBUNSHO_NOUKIYOTEIBI6;
	}

   /**
	* CHUUBUNSHO_MITSUMORISHONO7 見積書NOを設定
	*
	* @param CHUUBUNSHO_MITSUMORISHONO7 見積書NO
	*/
	public void setCHUUBUNSHO_MITSUMORISHONO7(String CHUUBUNSHO_MITSUMORISHONO7) {
		this.CHUUBUNSHO_MITSUMORISHONO7 = CHUUBUNSHO_MITSUMORISHONO7;
	}

   /**
	* CHUUBUNSHO_MITSUMORISHONO7 見積書NOを取得
	*
	* @return CHUUBUNSHO_MITSUMORISHONO7 見積書NO
	*/
	public String getCHUUBUNSHO_MITSUMORISHONO7() {
		return this.CHUUBUNSHO_MITSUMORISHONO7;
	}

   /**
	* CHUUBUNSHO_MITSUMORIKINGAKU8 見積金額を設定
	*
	* @param CHUUBUNSHO_MITSUMORIKINGAKU8 見積金額
	*/
	public void setCHUUBUNSHO_MITSUMORIKINGAKU8(String CHUUBUNSHO_MITSUMORIKINGAKU8) {
		this.CHUUBUNSHO_MITSUMORIKINGAKU8 = CHUUBUNSHO_MITSUMORIKINGAKU8;
	}

   /**
	* CHUUBUNSHO_MITSUMORIKINGAKU8 見積金額を取得
	*
	* @return CHUUBUNSHO_MITSUMORIKINGAKU8 見積金額
	*/
	public String getCHUUBUNSHO_MITSUMORIKINGAKU8() {
		return this.CHUUBUNSHO_MITSUMORIKINGAKU8;
	}

   /**
	* CHUUBUNSHO_SHOUHINSOUGAKUJPY9 商品総額JPYを設定
	*
	* @param CHUUBUNSHO_SHOUHINSOUGAKUJPY9 商品総額JPY
	*/
	public void setCHUUBUNSHO_SHOUHINSOUGAKUJPY9(String CHUUBUNSHO_SHOUHINSOUGAKUJPY9) {
		this.CHUUBUNSHO_SHOUHINSOUGAKUJPY9 = CHUUBUNSHO_SHOUHINSOUGAKUJPY9;
	}

   /**
	* CHUUBUNSHO_SHOUHINSOUGAKUJPY9 商品総額JPYを取得
	*
	* @return CHUUBUNSHO_SHOUHINSOUGAKUJPY9 商品総額JPY
	*/
	public String getCHUUBUNSHO_SHOUHINSOUGAKUJPY9() {
		return this.CHUUBUNSHO_SHOUHINSOUGAKUJPY9;
	}

   /**
	* CHUUBUNSHO_NOUNYUUBI10 納入日を設定
	*
	* @param CHUUBUNSHO_NOUNYUUBI10 納入日
	*/
	public void setCHUUBUNSHO_NOUNYUUBI10(String CHUUBUNSHO_NOUNYUUBI10) {
		this.CHUUBUNSHO_NOUNYUUBI10 = CHUUBUNSHO_NOUNYUUBI10;
	}

   /**
	* CHUUBUNSHO_NOUNYUUBI10 納入日を取得
	*
	* @return CHUUBUNSHO_NOUNYUUBI10 納入日
	*/
	public String getCHUUBUNSHO_NOUNYUUBI10() {
		return this.CHUUBUNSHO_NOUNYUUBI10;
	}

   /**
	* SHAIN_SHAINMEI11 社員名を設定
	*
	* @param SHAIN_SHAINMEI11 社員名
	*/
	public void setSHAIN_SHAINMEI11(String SHAIN_SHAINMEI11) {
		this.SHAIN_SHAINMEI11 = SHAIN_SHAINMEI11;
	}

   /**
	* SHAIN_SHAINMEI11 社員名を取得
	*
	* @return SHAIN_SHAINMEI11 社員名
	*/
	public String getSHAIN_SHAINMEI11() {
		return this.SHAIN_SHAINMEI11;
	}

   /**
	* KAISHA_KAISHAMEI12 会社名を設定
	*
	* @param KAISHA_KAISHAMEI12 会社名
	*/
	public void setKAISHA_KAISHAMEI12(String KAISHA_KAISHAMEI12) {
		this.KAISHA_KAISHAMEI12 = KAISHA_KAISHAMEI12;
	}

   /**
	* KAISHA_KAISHAMEI12 会社名を取得
	*
	* @return KAISHA_KAISHAMEI12 会社名
	*/
	public String getKAISHA_KAISHAMEI12() {
		return this.KAISHA_KAISHAMEI12;
	}


}