package com.wonderrobot.sfhanbaizaikokanrishisutemu.mapper.A013;


import org.apache.ibatis.annotations.Param;

/**
 * @project
 *     SF販売在庫管理システム
 * @comment
 *      id: A013T7afterupdateBUHINMapper
 * @version

 */

public interface A013T7afterupdateBUHINMapper {
	public int A013T7afterupdateBUHIN(@Param("ay3_BUHINSYOUSAIRINJIHYOU_KYAKUSAKIMEISHOU")String ay3_BUHINSYOUSAIRINJIHYOU_KYAKUSAKIMEISHOU, @Param("ay3_BUHINSYOUSAIRINJIHYOU_HINBAN")String ay3_BUHINSYOUSAIRINJIHYOU_HINBAN, @Param("ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU")String ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU, @Param("ay3_BUHINSYOUSAIRINJIHYOU_ASENBURIRAIN")String ay3_BUHINSYOUSAIRINJIHYOU_ASENBURIRAIN, @Param("ay3_BUHINSYOUSAIRINJIHYOU_KIKAIMEISHOU")String ay3_BUHINSYOUSAIRINJIHYOU_KIKAIMEISHOU, @Param("ay3_BUHINSYOUSAIRINJIHYOU_BUHINMEISHOU")String ay3_BUHINSYOUSAIRINJIHYOU_BUHINMEISHOU, @Param("ay3_BUHINSYOUSAIRINJIHYOU_SEISAKUSUU")int ay3_BUHINSYOUSAIRINJIHYOU_SEISAKUSUU, @Param("ay3_BUHINSYOUSAIRINJIHYOU_TANTOUSHA")String ay3_BUHINSYOUSAIRINJIHYOU_TANTOUSHA, @Param("ay3_BUHINSYOUSAIRINJIHYOU_MAISUU")String ay3_BUHINSYOUSAIRINJIHYOU_MAISUU, @Param("ay3_BUHINSYOUSAIRINJIHYOU_HIDZUKE")String ay3_BUHINSYOUSAIRINJIHYOU_HIDZUKE, @Param("BUHINCHUUBUNSHONO")String BUHINCHUUBUNSHONO, @Param("BUHINCHUUBUNSHOMEISAINO")String BUHINCHUUBUNSHOMEISAINO);
}