package com.wonderrobot.sfhanbaizaikokanrishisutemu.mapper.A013;


import org.apache.ibatis.annotations.Param;

/**
 * @project
 *     SF販売在庫管理システム
 * @comment
 *      id: A013T7afterinsertBUHINSYOUSAIMapper
 * @version

 */

public interface A013T7afterinsertBUHINSYOUSAIMapper {
	public int A013T7afterinsertBUHINSYOUSAI(@Param("ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUHINKUBUN")String ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUHINKUBUN, @Param("ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO")String ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO, @Param("ay7_BUHINSYOUSAIRINJIHYOU_HINMEI")String ay7_BUHINSYOUSAIRINJIHYOU_HINMEI, @Param("ay7_BUHINSYOUSAIRINJIHYOU_KOSUU")int ay7_BUHINSYOUSAIRINJIHYOU_KOSUU, @Param("ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU")int ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU, @Param("ay7_BUHINSYOUSAIRINJIHYOU_ZAISHITSU_KEISHIKI")String ay7_BUHINSYOUSAIRINJIHYOU_ZAISHITSU_KEISHIKI, @Param("ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUSHA")String ay7_BUHINSYOUSAIRINJIHYOU_SEISAKUSHA, @Param("ay7_BUHINSYOUSAIRINJIHYOU_BIKOU")String ay7_BUHINSYOUSAIRINJIHYOU_BIKOU, @Param("ay7_BUHINSYOUSAIRINJIHYOU_KIBOUNOUKI")String ay7_BUHINSYOUSAIRINJIHYOU_KIBOUNOUKI, @Param("ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUTANKA")double ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUTANKA, @Param("ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUHIDZUKE")String ay7_BUHINSYOUSAIRINJIHYOU_KOUNYUUHIDZUKE, @Param("ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAHIDZUKE")String ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAHIDZUKE, @Param("ay7_BUHINSYOUSAIRINJIHYOU_SHOUKEI")double ay7_BUHINSYOUSAIRINJIHYOU_SHOUKEI, @Param("ay7_BUHINSYOUSAIRINJIHYOU_TOUROKUSHAID")String ay7_BUHINSYOUSAIRINJIHYOU_TOUROKUSHAID, @Param("ay7_BUHINSYOUSAIRINJIHYOU_BIKOU1")String ay7_BUHINSYOUSAIRINJIHYOU_BIKOU1, @Param("ay7_BUHINSYOUSAIRINJIHYOU_HITSUYOU")String ay7_BUHINSYOUSAIRINJIHYOU_HITSUYOU, @Param("ay7_BUHINSYOUSAIRINJIHYOU_TEHAI")String ay7_BUHINSYOUSAIRINJIHYOU_TEHAI, @Param("ay7_BUHINSYOUSAIRINJIHYOU_KANRYOU")String ay7_BUHINSYOUSAIRINJIHYOU_KANRYOU, @Param("ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU1")int ay7_BUHINSYOUSAIRINJIHYOU_SOUKOSUU1, @Param("ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAYOTEIBI")String ay7_BUHINSYOUSAIRINJIHYOU_NYUUKAYOTEIBI, @Param("ay7_BUHINSYOUSAIRINJIHYOU_TANTOUSHAID")String ay7_BUHINSYOUSAIRINJIHYOU_TANTOUSHAID, @Param("ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO1")String ay7_BUHINSYOUSAIRINJIHYOU_HINBANNO1, @Param("BUHINCHUUBUNSHONO")String BUHINCHUUBUNSHONO, @Param("BUHINCHUUBUNSHOMEISAINO")String BUHINCHUUBUNSHOMEISAINO, @Param("ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU")String ay3_BUHINSYOUSAIRINJIHYOU_SHANAIKOUJIBANGOU);
}