package com.wonderrobot.sfhanbaizaikokanrishisutemu.entity.A006;



/**
 * @project
 *     null
 * @comment
 *     table id: A006L4I00016PrintEntity
 * @version

 */
public class A006L4I00016PrintEntity {
   /**
	*	 KKOJOUHOUICHIRAN_CHUUBUNSHONO1 注文書NO
	*/
	private String KKOJOUHOUICHIRAN_CHUUBUNSHONO1;
   /**
	*	 UHOUICHIRAN_SHUTSUNYUUKOJIKAN2 出入庫時間
	*/
	private String UHOUICHIRAN_SHUTSUNYUUKOJIKAN2;
   /**
	*	 HOUICHIRAN_SHUTSUNYUUKOJOUTAI3 出入庫状態
	*/
	private String HOUICHIRAN_SHUTSUNYUUKOJOUTAI3;
   /**
	*	 OJOUHOUICHIRAN_SHOUHINMEISHOU4 商品名称
	*/
	private String OJOUHOUICHIRAN_SHOUHINMEISHOU4;
   /**
	*	 SHUKKOJOUHOUICHIRAN_KAISHAMEI5 会社名
	*/
	private String SHUKKOJOUHOUICHIRAN_KAISHAMEI5;
   /**
	*	 UUKOSHUKKOJOUHOUICHIRAN_TAN_I6 単位
	*/
	private String UUKOSHUKKOJOUHOUICHIRAN_TAN_I6;
   /**
	*	 KOSHUKKOJOUHOUICHIRAN_SUURYOU7 数量
	*/
	private String KOSHUKKOJOUHOUICHIRAN_SUURYOU7;
   /**
	*	 UUKOSHUKKOJOUHOUICHIRAN_TANKA8 単価
	*/
	private String UUKOSHUKKOJOUHOUICHIRAN_TANKA8;
   /**
	*	 UKOSHUKKOJOUHOUICHIRAN_GOUKEI9 合計
	*/
	private String UKOSHUKKOJOUHOUICHIRAN_GOUKEI9;
   /**
	* KKOJOUHOUICHIRAN_CHUUBUNSHONO1 注文書NOを設定
	*
	* @param KKOJOUHOUICHIRAN_CHUUBUNSHONO1 注文書NO
	*/
	public void setKKOJOUHOUICHIRAN_CHUUBUNSHONO1(String KKOJOUHOUICHIRAN_CHUUBUNSHONO1) {
		this.KKOJOUHOUICHIRAN_CHUUBUNSHONO1 = KKOJOUHOUICHIRAN_CHUUBUNSHONO1;
	}

   /**
	* KKOJOUHOUICHIRAN_CHUUBUNSHONO1 注文書NOを取得
	*
	* @return KKOJOUHOUICHIRAN_CHUUBUNSHONO1 注文書NO
	*/
	public String getKKOJOUHOUICHIRAN_CHUUBUNSHONO1() {
		return this.KKOJOUHOUICHIRAN_CHUUBUNSHONO1;
	}

   /**
	* UHOUICHIRAN_SHUTSUNYUUKOJIKAN2 出入庫時間を設定
	*
	* @param UHOUICHIRAN_SHUTSUNYUUKOJIKAN2 出入庫時間
	*/
	public void setUHOUICHIRAN_SHUTSUNYUUKOJIKAN2(String UHOUICHIRAN_SHUTSUNYUUKOJIKAN2) {
		this.UHOUICHIRAN_SHUTSUNYUUKOJIKAN2 = UHOUICHIRAN_SHUTSUNYUUKOJIKAN2;
	}

   /**
	* UHOUICHIRAN_SHUTSUNYUUKOJIKAN2 出入庫時間を取得
	*
	* @return UHOUICHIRAN_SHUTSUNYUUKOJIKAN2 出入庫時間
	*/
	public String getUHOUICHIRAN_SHUTSUNYUUKOJIKAN2() {
		return this.UHOUICHIRAN_SHUTSUNYUUKOJIKAN2;
	}

   /**
	* HOUICHIRAN_SHUTSUNYUUKOJOUTAI3 出入庫状態を設定
	*
	* @param HOUICHIRAN_SHUTSUNYUUKOJOUTAI3 出入庫状態
	*/
	public void setHOUICHIRAN_SHUTSUNYUUKOJOUTAI3(String HOUICHIRAN_SHUTSUNYUUKOJOUTAI3) {
		this.HOUICHIRAN_SHUTSUNYUUKOJOUTAI3 = HOUICHIRAN_SHUTSUNYUUKOJOUTAI3;
	}

   /**
	* HOUICHIRAN_SHUTSUNYUUKOJOUTAI3 出入庫状態を取得
	*
	* @return HOUICHIRAN_SHUTSUNYUUKOJOUTAI3 出入庫状態
	*/
	public String getHOUICHIRAN_SHUTSUNYUUKOJOUTAI3() {
		return this.HOUICHIRAN_SHUTSUNYUUKOJOUTAI3;
	}

   /**
	* OJOUHOUICHIRAN_SHOUHINMEISHOU4 商品名称を設定
	*
	* @param OJOUHOUICHIRAN_SHOUHINMEISHOU4 商品名称
	*/
	public void setOJOUHOUICHIRAN_SHOUHINMEISHOU4(String OJOUHOUICHIRAN_SHOUHINMEISHOU4) {
		this.OJOUHOUICHIRAN_SHOUHINMEISHOU4 = OJOUHOUICHIRAN_SHOUHINMEISHOU4;
	}

   /**
	* OJOUHOUICHIRAN_SHOUHINMEISHOU4 商品名称を取得
	*
	* @return OJOUHOUICHIRAN_SHOUHINMEISHOU4 商品名称
	*/
	public String getOJOUHOUICHIRAN_SHOUHINMEISHOU4() {
		return this.OJOUHOUICHIRAN_SHOUHINMEISHOU4;
	}

   /**
	* SHUKKOJOUHOUICHIRAN_KAISHAMEI5 会社名を設定
	*
	* @param SHUKKOJOUHOUICHIRAN_KAISHAMEI5 会社名
	*/
	public void setSHUKKOJOUHOUICHIRAN_KAISHAMEI5(String SHUKKOJOUHOUICHIRAN_KAISHAMEI5) {
		this.SHUKKOJOUHOUICHIRAN_KAISHAMEI5 = SHUKKOJOUHOUICHIRAN_KAISHAMEI5;
	}

   /**
	* SHUKKOJOUHOUICHIRAN_KAISHAMEI5 会社名を取得
	*
	* @return SHUKKOJOUHOUICHIRAN_KAISHAMEI5 会社名
	*/
	public String getSHUKKOJOUHOUICHIRAN_KAISHAMEI5() {
		return this.SHUKKOJOUHOUICHIRAN_KAISHAMEI5;
	}

   /**
	* UUKOSHUKKOJOUHOUICHIRAN_TAN_I6 単位を設定
	*
	* @param UUKOSHUKKOJOUHOUICHIRAN_TAN_I6 単位
	*/
	public void setUUKOSHUKKOJOUHOUICHIRAN_TAN_I6(String UUKOSHUKKOJOUHOUICHIRAN_TAN_I6) {
		this.UUKOSHUKKOJOUHOUICHIRAN_TAN_I6 = UUKOSHUKKOJOUHOUICHIRAN_TAN_I6;
	}

   /**
	* UUKOSHUKKOJOUHOUICHIRAN_TAN_I6 単位を取得
	*
	* @return UUKOSHUKKOJOUHOUICHIRAN_TAN_I6 単位
	*/
	public String getUUKOSHUKKOJOUHOUICHIRAN_TAN_I6() {
		return this.UUKOSHUKKOJOUHOUICHIRAN_TAN_I6;
	}

   /**
	* KOSHUKKOJOUHOUICHIRAN_SUURYOU7 数量を設定
	*
	* @param KOSHUKKOJOUHOUICHIRAN_SUURYOU7 数量
	*/
	public void setKOSHUKKOJOUHOUICHIRAN_SUURYOU7(String KOSHUKKOJOUHOUICHIRAN_SUURYOU7) {
		this.KOSHUKKOJOUHOUICHIRAN_SUURYOU7 = KOSHUKKOJOUHOUICHIRAN_SUURYOU7;
	}

   /**
	* KOSHUKKOJOUHOUICHIRAN_SUURYOU7 数量を取得
	*
	* @return KOSHUKKOJOUHOUICHIRAN_SUURYOU7 数量
	*/
	public String getKOSHUKKOJOUHOUICHIRAN_SUURYOU7() {
		return this.KOSHUKKOJOUHOUICHIRAN_SUURYOU7;
	}

   /**
	* UUKOSHUKKOJOUHOUICHIRAN_TANKA8 単価を設定
	*
	* @param UUKOSHUKKOJOUHOUICHIRAN_TANKA8 単価
	*/
	public void setUUKOSHUKKOJOUHOUICHIRAN_TANKA8(String UUKOSHUKKOJOUHOUICHIRAN_TANKA8) {
		this.UUKOSHUKKOJOUHOUICHIRAN_TANKA8 = UUKOSHUKKOJOUHOUICHIRAN_TANKA8;
	}

   /**
	* UUKOSHUKKOJOUHOUICHIRAN_TANKA8 単価を取得
	*
	* @return UUKOSHUKKOJOUHOUICHIRAN_TANKA8 単価
	*/
	public String getUUKOSHUKKOJOUHOUICHIRAN_TANKA8() {
		return this.UUKOSHUKKOJOUHOUICHIRAN_TANKA8;
	}

   /**
	* UKOSHUKKOJOUHOUICHIRAN_GOUKEI9 合計を設定
	*
	* @param UKOSHUKKOJOUHOUICHIRAN_GOUKEI9 合計
	*/
	public void setUKOSHUKKOJOUHOUICHIRAN_GOUKEI9(String UKOSHUKKOJOUHOUICHIRAN_GOUKEI9) {
		this.UKOSHUKKOJOUHOUICHIRAN_GOUKEI9 = UKOSHUKKOJOUHOUICHIRAN_GOUKEI9;
	}

   /**
	* UKOSHUKKOJOUHOUICHIRAN_GOUKEI9 合計を取得
	*
	* @return UKOSHUKKOJOUHOUICHIRAN_GOUKEI9 合計
	*/
	public String getUKOSHUKKOJOUHOUICHIRAN_GOUKEI9() {
		return this.UKOSHUKKOJOUHOUICHIRAN_GOUKEI9;
	}


}